book_database/urls.py
from django.urls import path
from . import views

app_name = "book_database"

urlpatterns = [
    path("", views.book_homepage_view, name="homepage"),
    path("add_like", views.book_add_like, name="add_like"),
    path("top_five", views.top_five, name="top_five"),
    path("get_likes/<str:book_id>", views.get_likes, name="get_likes")
]

mini_profile/urls.py
from django.urls import path
from . import views

app_name = "mini_profile"

urlpatterns = [
    path("", views.mini_profile_view, name="mini_profile")
]

status_update/urls.py
from django.urls import path
from . import views

app_name = "status_update"

urlpatterns = [
    path("", views.list_view, name="list_view"),
    path("confirm/", views.confirm_view, name="confirm_view"),
    path("add/", views.add_view, name="add_view"),
    path("change_color/", views.change_color_view , name="change_color")
]

story_7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("status_update.urls")),
    path("story-8/", include("mini_profile.urls")),
    path("story-9/", include("book_database.urls"))
]

book_database/models.py
from django.db import models

class Book(models.Model):
    book_id = models.CharField(unique = True, max_length = 100)
    title = models.CharField(max_length = 100)
    cover_link = models.URLField(unique = True)
    description = models.TextField()
    likes = models.IntegerField(default=1)

    def __str__(self):
        return "{} - {}".format(self.title, self.book_id)

mini_profile/models.py
from django.db import models

# Create your models here.

status_update/models.py
from django.db import models

class StatusUpdate(models.Model):
    name = models.TextField(max_length=50)
    description = models.TextField(max_length=500)
    color_code = models.IntegerField(default=0)

    def __str__(self):
        return f"({self.name}) - {self.description[:20]}..."

status_update/forms.py
from django import forms
from .models import StatusUpdate

class StatusUpdateForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        "class" : "form-control",
        "id" : "name",
        "placeholder" : "John Doe"
    }))
    description = forms.CharField(widget=forms.Textarea(attrs={
        "class" : "form-control",
        "id" : "description",
        "rows" : 3,
        "placeholder" : "I feel happy today!"
    }))
    class Meta:
        model = StatusUpdate
        exclude = ["color_code"]

book_database/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.core import serializers
from .models import Book
import json

def book_homepage_view(request):
    return render(request, "book_database/index.html")

def book_add_like(request):
    if request.method == "POST":
        book_id = request.POST["book_id"]
        try:
            selected_book = Book.objects.get(book_id = book_id)
            selected_book.likes += 1
            selected_book.save()
        except:
            Book.objects.create(
                title = request.POST["title"],
                book_id = request.POST["book_id"],
                cover_link = request.POST["cover_link"],
                description = request.POST["description"]
            )
    return redirect("book_database:homepage")

def top_five(request):
    return JsonResponse({"data" : list(Book.objects.order_by("-likes")[:5].values())})

def get_likes(request,book_id):
    try:
        selected_book = Book.objects.get(book_id = book_id)
        return JsonResponse({"likes" : selected_book.likes})
    except:
        return JsonResponse({"likes" : 0})

mini_profile/views.py
from django.shortcuts import render, HttpResponse

def mini_profile_view(request):
    return render(request, "mini_profile/index.html")

status_update/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import StatusUpdate
from .forms import StatusUpdateForm

def list_view(request):
    status_update_query = [(status, status.color_code % 5) for status in StatusUpdate.objects.all()]
    status_update_query = sorted(status_update_query, key = lambda status: -status[0].id)
    context = {
        "status_update_query" : status_update_query,
        "page" : "list_view",
        "form" : StatusUpdateForm
    }
    return render(request, "status_update/index.html", context)

def confirm_view(request):
    if request.method == "POST":
        context = {
            "name" : request.POST["name"],
            "description" : request.POST["description"],
        }
        return render(request, "status_update/confirm.html", context)

    return redirect("status_update:list_view")

def add_view(request):
    if request.method == "POST":
        form = StatusUpdateForm(request.POST)
        if form.is_valid():
            status = form.save(commit=False)
            status.color_code = 0
            status.save()
    return redirect("status_update:list_view")

def change_color_view(request):
    if request.method == "POST":
        idx = request.POST["idx"]
        selected_status = StatusUpdate.objects.get(id=idx)
        selected_status.color_code += 1
        selected_status.save()
    return redirect("status_update:list_view")

book_database/templates/book_database/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- External CSS -->
    <link rel="stylesheet" href="{% static 'book_database/css/styles.css' %}">

    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <title>Book Database</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-main1">
        <div class="container">
            <a class="navbar-brand" href="#">Book Database</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <button type="button" id="modal-btn" class="ml-auto btn btn-secondary" data-toggle="modal" data-target="#exampleModalLong">
                  Top 5
                </button>
            </div>
        </div>
    </nav>
    {% block content %}
    
    {% endblock %}
    <script src="{% static 'book_database/js/script.js' %}"></script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html> 

book_database/templates/book_database/index.html
{% extends 'book_database/base.html' %}
{% load static %}

{% block content %}
<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header bg-main1 text-light border-0">
          <h5 class="modal-title" id="exampleModalLongTitle">Top 5 liked books</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body bg-main2 text-light">
          <div class="w-100 h-100 row m-0 p-0" id="modal-list">
            
          </div>
        </div>
        <div class="modal-footer bg-main1 border-0">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

<div class="jumbotron bg-main2 text-light rounded-0 m-0">
    <div class="container">
        <h1 class="display-4">Book Database</h1>
        <p class="lead">Database provided by Google, Website made by Steven for the 9th Web Design and Programming Assignment</p>
        <hr class="my-4">
        <p>Search for the information of a book that you want here :)</p>
        <p class="lead">
        <div class="d-flex">
            <input type="text" id="book-form" class="form-control w-25 mr-1" placeholder="Book Title">
            <button class="btn btn-main1" id="find-btn" role="button">Search</button>
        </div>
        </p>
    </div>
</div>

<section class="bg-main3 text-light p-3 result-section">
    <h3 class="text-center p-0 m-0">Search Results (<span id="found-amount">?</span>):</h3>
    
    <div class="d-flex flex-column align-items-center" id="book-list">

        <h1 class="m-5">Search for a book first UwU</h1>

    </div>
</section>

<script>
    $(document).ready(function(){
        // Get JSON book
        $("#find-btn").click(() => {
            let searched_title = $("#book-form").val()

            if (searched_title == "") {
                alert("Please input a valid name")
            } else {
                $("#book-list").empty()
                try {
                    $.get(`https://www.googleapis.com/books/v1/volumes?q=${searched_title}`, (res) => {
                        for (book of res.items) {
                            update_ul(book)
                        }

                        $("#found-amount").text(res.items.length)
                    })
                } catch {
                    alert("Book not found.")
                }
                
            }
        })

        // Update ul
        function update_ul(book) {
            var ul = $("#book-list")
            try {
                var thumbnail_link = book.volumeInfo.imageLinks.thumbnail
            } catch {
                var thumbnail_link = "https://upload.wikimedia.org/wikipedia/commons/f/fc/No_picture_available.png"
            }
            var description = book.volumeInfo.description ? book.volumeInfo.description : "No description available"

            var likes
            $.get( `/story-9/get_likes/${book.id}`, (res) => {
                likes = res.likes
            }).done(() => {
                    ul.append(
                    `<div class="card w-75 border-dark m-3">
                        <h3 class="card-header bg-main1 text-center text-left-lg">${book.volumeInfo.title}</h3>
                        <div class="card-body bg-main2">
                            <div class="row">
                                <div class="col-lg-3 col-12 d-flex align-items-center justify-content-center">
                                    <img class="mr-3 book-cover" src="${thumbnail_link}">
                                </div>
                                <div class="col-lg-9 col-12 book-info">
                                    <h5 class="card-title">Published on ${book.volumeInfo.publishedDate}</h5>
                                    <p class="card-text text-justify">${description}</p>
                                    <button class="like-btn btn btn-main1" type="submit" title="${book.volumeInfo.title}" book_id="${book.id}" cover_link="${thumbnail_link}" description="${description}">Like this book</button>
                                    <h5 class="d-inline">Likes : ${likes}</h5>
                                </div>
                            </div>
                        </div>
                    </div>`
                )
            })


            
        }

        // Like button
        $("#book-list").click((e) => {
            if ($(e.target).hasClass("like-btn")) {
                var title = $(e.target).attr("title")
                var book_id = $(e.target).attr("book_id")
                var description = $(e.target).attr("description")
                var thumbnail_link = $(e.target).attr("cover_link")

                $.post("{% url 'book_database:add_like' %}", {
                    csrfmiddlewaretoken : "{{csrf_token}}",
                    title : title,
                    book_id : book_id,
                    cover_link : thumbnail_link,
                    description : description
                }).done(() => {
                    $.get(`/story-9/get_likes/${book_id}`, (res) => {
                        $(e.target).next().text(`Likes: ${res.likes}`)
                    })
                })
            }
        })

        // Modal Button
        $("#modal-btn").click(() => {
            $("#modal-list").empty()
            $.get("{% url 'book_database:top_five' %}", (res) => {
                for (book of res.data) {
                    $("#modal-list").append(
                        `
                        <div class="col-12 d-flex mt-2">
                            <img class="book-cover" src="${book.cover_link}">
                            <div class="p-2">
                                <h3>${book.title}</h3>
                                <h5>Likes: ${book.likes}</h5>
                            </div>
                        </div>
                        `
                    )
                }
            })
        })
    });
</script>

{% endblock content %}

mini_profile/templates/mini_profile/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Mini Profile</title>
    <link href="https://fonts.googleapis.com/css2?family=Comic+Neue&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'mini_profile/css/styles.css' %}">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark navbar-footer-bg shadow-lg">
        <div class="container">
            <a class="navbar-brand" href="#">Steven's Profile</a>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <footer class="footer navbar-footer-bg text-light d-flex justify-content-center align-items-center shadow-lg">
        Made by Steven - 2020
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'mini_profile/js/script.js' %}"></script>
</body>
</html>

mini_profile/templates/mini_profile/index.html
{% extends "mini_profile/base.html" %}
{% load static %}
{% block content %}

    <section class="h-main container-fluid" id="main-bg">
        <div class="row">
            <div class="col-lg-6 col-sm-12 h-main d-flex justify-content-center align-items-center flex-column">
                    <img class="w-50 bg-dark p-2 rounded-lg" src="{% static 'mini_profile/images/8259-min.jpg' %}">
                    <div class="mt-2 bg-dark text-light p-1 rounded-lg">
                        Hello, I'm Steven
                    </div>
            </div>
            <div class="col-lg-6 col-sm-12 h-main p-2">
                <div id="accordion">
                    <h3 position="0" class="p-2 m-0 accordion-tab text-light">
                        About me
                        <span class="mx-1 float-right down" id="down">
                            Down
                        </span>
                        <span class="mx-1 float-right up" id="up">
                            Up
                        </span>
                    </h3>
                    <p position="0" class="p-1 m-0 bg-success text-light">
                        Computer Science student, Interested in web development and mathematics, and is also fond of Japanese culture and language OwO
                    </p>
                    <h3 position="1" class="p-2 m-0 accordion-tab text-light">
                        What can I do?
                        <span class="mx-1 float-right down" id="down">
                            Bawah
                        </span>
                        <span class="mx-1 float-right up" id="up">
                            Atas
                        </span>
                    </h3>
                    <p position="1" class="p-1 m-0 bg-success text-light">
                        I can write code in Python, Javascript, Java, and Ruby
                    </p>
                    <h3 position="2" class="p-2 m-0 accordion-tab text-light">
                        Where do I live?
                        <span class="mx-1 float-right down" id="down">
                            した
                        </span>
                        <span class="mx-1 float-right up" id="up">
                            うえ
                        </span>
                    </h3>
                    <p position="2" class="p-1 m-0 bg-success text-light">
                        I live in North Jakarta, but my University is in Depok, West Java
                    </p>
                    <h3 position="3" class="p-2 m-0 accordion-tab text-light">
                        Can I get to know you?
                        <span class="mx-1 float-right down" id="down">
                            ↓
                        </span>
                        <span class="mx-1 float-right up" id="up">
                            ↑
                        </span>
                    </h3>
                    <p position="3" class="p-1 m-0 bg-success text-light">
                        Yes, follow my instagram, @stevensim226
                    </p>
                    <h3 position="4" class="p-2 m-0 accordion-tab text-light">
                        Where did you take that pic?
                        <span class="mx-1 float-right down" id="down">
                            下
                        </span>
                        <span class="mx-1 float-right up" id="up">
                            上
                        </span>
                    </h3>
                    <p position="4" class="p-1 m-0 bg-success text-light">
                        Tennoji Park, Osaka, Japan
                        <br>
                        天王寺公園、大阪、日本
                    </p>
                </div>

                <button class="btn btn-primary mt-2" id="change-theme-btn">Change theme here UwU</button>
            </div>
        </div>
    </section>

{% endblock %}

status_update/templates/status_update/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- External CSS -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Status Update</title>
  </head>
  <body class="bg-main2">

    <nav class="navbar navbar-expand-lg navbar-light bg-main1">
        <a class="navbar-brand" href="{% url 'status_update:list_view' %}">What's on your mind?</a>  
        {% if page == "list_view" %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active d-flex justify-content-center align-items-center">
            <button class="btn bg-main2 text-dark" id="new_status" data-toggle="modal" data-target="#exampleModal">Update Status</button>
            </li>
        </ul>
        </div>
        {% endif %}
    </nav>

    {% block content %}
    {% endblock %}

      <footer class="bg-main3 text-light d-flex justify-content-center align-items-center">
          <p class="m-0">Made by Steven - 2020</p>
      </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

status_update/templates/status_update/confirm.html
{% extends "status_update/base.html" %}
{% block content %}

<section class="h-nav-footer container py-3 d-flex justify-content-center">
    <div class="w-75">
        <div class="card-header bg-main3 text-light">
          Confirmation
        </div>
        <div class="card-body bg-main1">
          <h5 class="card-title">You are about to post this status update:</h5>
          <p class="card-text m-0 p-0">Written by : {{name}}</p>
          <p class="card-text bg-light rounded-sm p-1">
              {{description}}
          </p>

            <div class="d-flex justify-content-around">
                <a href="{% url 'status_update:list_view' %}" class="btn btn-danger w-50 m-1">Cancel</a>
                <form action="{% url 'status_update:add_view' %}" method="POST" class="w-50">
                    {% csrf_token %}
                    <input type="hidden" value="{{name}}" name="name">
                    <input type="hidden" value="{{description}}" name="description">
                    <button type="submit" class="btn btn-success w-100 m-1">Post</button>
                </form>
            </div>
        </div>
      </div>
  </section>

{% endblock %}

status_update/templates/status_update/index.html
{% extends "status_update/base.html" %}
{% block content %}

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header bg-main1">
          <h5 class="modal-title" id="exampleModalLabel">New status update</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body bg-main2">
          <form action="{% url 'status_update:confirm_view' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label for="name">Name</label>
              {{form.name}}
            </div>
            <div class="form-group">
              <label for="description">What's on your mind?</label>
              {{form.description}}
            </div>
          
        </div>
          <div class="modal-footer bg-main1">
            <button type="submit" class="btn btn-success">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>

<section class="h-nav-footer container py-3">
    <div class="row">
        {% for status in status_update_query %}
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="m-1 p-1 text-light rounded-sm" style="
              background-color:
              {% if status.1 == 0 %}
              red
              {% elif status.1 == 1 %}
              blue
              {% elif status.1 == 2 %}
              gold
              {% elif status.1 == 3 %}
              purple
              {% elif status.1 == 4 %}
              green
              {% endif %}
            ">
            Written by: {{status.0.name}}
            <p class="bg-light m-1 p-1 text-dark rounded-sm">
                {{status.0.description}}
            </p>
            <form action="{% url 'status_update:change_color'%}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="idx" value="{{status.0.id}}">
              <button class="btn btn-primary w-100" type="submit">
                Change Color OwO
              </button>
            </form>
            </div>
        </div>
        {% endfor %}            
    </div>
</section>

{% endblock %}